#!/usr/bin/env sh

echo "Adding configs from the dotfiles repo..."

# Delete old configs
cd ~/
rm -r .vimrc .zshrc .ncmpcpp .local
# Add new configs
cd ~/DOTFILES/dotfiles
cp -r .vimrc .zshrc .ncmpcpp .local ~/ &>/dev/null

# Delete old configs
cd ~/.config/
rm -r alacritty bspwm dmenu dunst fish gtk-3.0 i3 leftwm neofetch nvim picom qutebrowser rofi sxhkd termite Thunar xfce4 zathura emoji
find polybar -type f -delete

# Add the polybar config
cd ~/DOTFILES/dotfiles/.config/

if [ "$GDMSESSION" = "bspwm" ]; then
	cd polybar
	cp config ~/.config/polybar/
	cp launch.sh ~/.config/polybar/
	cp -r scripts ~/.config/polybar/
fi

# Add new configs
cd ~/DOTFILES/dotfiles/.config/
cp -r alacritty bspwm dmenu dunst fish gtk-3.0 i3 leftwm neofetch nvim picom qutebrowser rofi sxhkd termite Thunar xfce4 zathura emoji ~/.config/ &>/dev/null

echo "Done!"
