#!/usr/bin/env sh

echo "Adding configs from the dotfiles repo..."

cd ~/DOTFILES/dotfiles
cp -r .vimrc .zshrc .ncmpcpp .scripts ~/ &>/dev/null

cd ~/DOTFILES/dotfiles/.config/

if [ "$GDMSESSION" = "bspwm" ]; then
	cd polybar-bspwm
	cp config ~/.config/polybar/
	cp launch.sh ~/.config/polybar/
	cp -r scripts ~/.config/polybar/	
elif [ "$GDMSESSION" = "i3" ]; then
	cd polybar-i3
	cp config ~/.config/polybar/
	cp launch.sh ~/.config/polybar/
	cp -r scripts ~/.config/polybar/	
fi

cd ~/DOTFILES/dotfiles/.config/

cp -r alacritty bspwm dunst i3 picom ranger rofi sxhkd termite wallpapers zathura emoji ~/.config/ &>/dev/null

echo "Done."
