#!/bin/sh
#     _
#    | |__  ___ _ ____      ___ __ ___
#    | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#    | |_) \__ \ |_) \ V  V /| | | | | |
#    |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#              |_|

# LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           20
bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# BSPWM coloring
bspc config normal_border_color		"#5c6370"
bspc config active_border_color		"#5c6370"
bspc config focused_border_color	"#56b6c2"
bspc config presel_feedback_color	"#56b6c2"
#bspc config urgent_border_color 	"#e06c75"

# Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Fullscreen applications
#bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
#bspc rule -a Vlc state=fullscreen
#bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

# Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
#bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Nitrogen state=floating
#bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating

# Tiled applications
#bspc rule -a Gnome-disks state=tiled
#bspc rule -a Xfce4-settings-manager state=tiled

# Open applications on specific workspaces
bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a Chromium desktop='^1'  follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Atom desktop='^3' follow=on
bspc rule -a Meld desktop='^8' follow=on
bspc rule -a vlc desktop='^5'  follow=on
bspc rule -a mpv desktop='^5'  follow=on
bspc rule -a Vivaldi-stable desktop='^1' follow=on
bspc rule -a Gpick desktop='^9' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Thunar desktop='^2' follow=on
bspc rule -a Nitrogen desktop='^6' follow=on
bspc rule -a Spotify desktop='^4' follow=on

# Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

# Polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

### External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
